version: '24.0.6'
services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DemoPostgreSQL
    networks:
      - freecodecamp

  #Create another container for test
  test-db:
    image: postgres:13
    container_name: test-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DemoPostgreSQL
    networks:
      - freecodecamp
networks:
  freecodecamp: